# -*- coding: utf-8 -*-
"""ЛР ИБА задание 1 17.04.2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16DpQrNsYQTqR3VjZTgjcs5YEsdhR00O-
"""

import tensorflow as tf
import numpy as np

#Список бандитов.
bandits = []
#кол-во бандитов
k = 5 
j = 0
while j < k:
    i = np.random.randn(1)
    bandits.append(i)
    j+=1
print (bandits)
num_bandits = len(bandits)
def pullBandit(bandit):
    result = np.random.randn(1)
    if result > bandit:
        return 1
    else:
        return -1

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

weights = tf.Variable(tf.ones([num_bandits]))
chosen_action = tf.argmax(weights,0)

reward_holder = tf.placeholder(shape=[1],dtype=tf.float32)
action_holder = tf.placeholder(shape=[1],dtype=tf.int32)
responsible_weight = tf.slice(weights,action_holder,[1])
loss = -(tf.log(responsible_weight)*reward_holder)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
update = optimizer.minimize(loss)

total_episodes = 1000 #Количество итераций обучения
total_reward = np.zeros(num_bandits) 
e = 0.1 #Вероятность случайного выбора
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    i = 0
    while i < total_episodes:
                
        if np.random.rand(1) < e:
            action = np.random.randint(num_bandits)
        else:
            action = sess.run(chosen_action)
    
        reward = pullBandit(bandits[action]) 
        
        _,resp,ww = sess.run([update,responsible_weight,weights], 
                      feed_dict={reward_holder:[reward],action_holder:[action]})
        
        total_reward[action] += reward
        if i % 50 == 0:
            print("Общий выигрыш сейчас равен " + str(num_bandits) + 
            " бандитов: " + str(total_reward))
        i+=1
print("Агент думает, что бандит №" + str(np.argmax(ww)+1) + " лучший")